web:
  extends:
    file: docker-compose.yml
    service: web
  restart: always
  links:
    - mongo
  environment:
    - VIRTUAL_HOST=remerge.net
    - VIRTUAL_PORT=80
    - NODE_ENV=production
  #command: node --harmony src/server.js
mongo:
  extends:
    file: docker-compose.yml
    service: mongo
  restart: always
  volumes:
    - ./data:/data
