web:
  build: .
  links:
    - mongo
  ports:
    - "80:3000"
    - "35729:35729"
  volumes:
    - .:/srv/blog
  environment:
    - NODE_ENV=development
  command:
    npm run dev
mongo:
  image: mongo:3.0
  ports:
    - "27017:27017"
  volumes:
    - ./data:/data