web:
  extends:
    file: docker-compose.yml
    service: web
  links:
    - mongo
  ports:
    - "3000:3000"
  environment:
    - VIRTUAL_HOST=remerge.net
    - VIRTUAL_PORT=3000
    - NODE_ENV=production
  #command: node --harmony src/server.js
mongo:
  extends:
    file: docker-compose.yml
    service: mongo
